name: Tonlib Android

on: [push, pull_request, workflow_dispatch, workflow_call]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install system libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git cmake ninja-build automake libtool texinfo autoconf libgflags-dev \
        zlib1g-dev libreadline-dev libmicrohttpd-dev pkg-config libgsl-dev python3 python3-dev \
        libtool autoconf libsecp256k1-dev

    -  name: Install llvm-21
       run: |
        lsb_release -a
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-21 main" | sudo tee /etc/apt/sources.list.d/llvm.list
        sudo apt-get -y update
        sudo apt-get install -y clang-21

    - name: Cache Android NDK
      id: cache-android-ndk
      uses: actions/cache@v4
      with:
        path: android-ndk-r25b
        key: ${{ runner.os }}-${{ runner.arch }}-ubuntu-22.04-cache-android-ndk-${{ hashFiles('**/assembly/android/build-android-tonlib.sh') }}

    - name: Build TON
      run: |
        git submodule sync --recursive
        git submodule update
        cp assembly/android/build-android-tonlib.sh .
        chmod +x build-android-tonlib.sh
        ./build-android-tonlib.sh -a

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-android-tonlib
        path: artifacts
