name: C/C++ CI macOS-10.15 Compile

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:      
        submodules: 'recursive'
    - name: Compile OpenSSL
      run: |
        git clone https://github.com/openssl/openssl openssl_1_1_1
        cd openssl_1_1_1
        git checkout OpenSSL_1_1_1-stable
        ./Configure --prefix=/usr/local/macos darwin64-x86_64-cc -static -mmacosx-version-min=10.15
        make build_libs -j4

    - name: Build all
      run: |
        rootPath=`pwd`
        mkdir build
        cd build
        cmake -DOPENSSL_FOUND=1 -DOPENSSL_INCLUDE_DIR=$rootPath/openssl_1_1_1/include -DOPENSSL_CRYPTO_LIBRARY=$rootPath/openssl_1_1_1/libcrypto.a -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.15 -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_BUILD_TYPE=Release ..
        make -j4

    - name: Find & copy binaries
      run: |
        rsync -r --exclude 'CMakeFiles' --exclude 'Makefile' --exclude '*.a' --exclude '*.cmake' --exclude 'third-party' --exclude 'test-*' --exclude '*.cc' --exclude '*.json' --exclude '*.txt' build/* artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-macos-binaries
        path: artifacts
