name: "Static build and unit tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: ton
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix develop .#packages.x86_64-linux-musl.ton \
          --command bash -e -c '
            cmake $cmakeFlags -S . -B build

            cmake --build build -j4

            pushd build
            # test-tdutils: locale trouble w/static build
            ctest -E "test-tdutils"
            popd

            cmake --install build --prefix install
            ./packages/deb.sh install packages/deb/ton'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-binaries
        path: install
