name: TON WASM Compile

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install libraries
      run: |
        sudo apt update
        sudo apt install -y build-essential git make cmake ninja-build clang libgflags-dev zlib1g-dev libssl-dev libreadline-dev libmicrohttpd-dev pkg-config libgsl-dev python3 python3-dev python3-pip nodejs

    - name: Configure & Build
      run: |
        cd .github/script
        ./fift-func-wasm-build-ubuntu.sh

    - name: Find & copy binaries
      run: |
        mkdir artifacts
        ls build/crypto
        cp build/crypto/fift* artifacts
        cp build/crypto/func* artifacts
        cp build/crypto/tlbc* artifacts
        cp build/emulator/emulator-emscripten* artifacts
        cp -R crypto/smartcont artifacts
        cp -R crypto/fift/lib artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-wasm-binaries
        path: artifacts