name: MacOS TON build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build TON
      run: |
        git submodule sync --recursive
        git submodule update
        cp assembly/nix/build-macos-nix.sh .
        chmod +x build-macos-nix.sh
        ./build-macos-nix.sh -t

    - name: Simple binaries test
      run: |
        sudo mv /nix/store /nix/store2
        artifacts/validator-engine -V
        artifacts/lite-client -V
        artifacts/fift -V
        artifacts/func -V
        artifacts/tolk -v

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-x86_64-macos-binaries
        path: artifacts
